spring:
   jpa:
     hibernate:
       ddl-auto: create
       dialect: MariaDB53Dialect
       use-new-id-generator-mappings: true
     generate-ddl: true
     show-sql: true
     properties:
       hibernate:
         format_sql: true

   datasource:
     driver-class-name: org.mariadb.jdbc.Driver
     url: jdbc:mariadb://localhost:3306/visitor?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
     username: root
     password: mariadb
     initialization-mode: always